name: Build and Deploy NGINX Docker Image

on:
  push:
    branches:
      - dev

jobs:
  lint_test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

          #      - name: Lint Dockerfile
          # run: docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-dev:latest .

      - name: Test NGINX container
        run: |
          docker run -d -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/nginx-dev:latest .
          sleep 10
          curl --fail http://localhost:8080

  deploy:
    needs: lint_test_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-dev:latest

      - name: Deploy to EC2 using Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
          # Assuming your Terraform configuration includes the EC2 instance
          # deployment and pulls the Docker image from Docker Hub

