name: Build NGINX Docker Image for Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t nginx-dev:latest .

      - name: Test NGINX container
        run: docker run -d -p 8080:80 nginx-dev:latest

