name: Build and Tag Release Docker Image

on:
  push:
    branches:
      - release/*

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Release Tag
        run: |
          git fetch --all
          TAG="v1.0.$(git rev-list --count HEAD)"
          git tag $TAG
          git push origin $TAG


