name: Create and Push Tag

on:
  push:
    branches:
      - release

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Determine tag version
        id: tag_version
        run: |
          # Get the latest tag version and increment it
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          new_tag=$(echo $latest_tag | awk -F. '{print $1"."$2"."$3+1}')
          echo "New tag: $new_tag"
          echo "::set-output name=tag::$new_tag"

      - name: Create new tag
        run: |
          git tag ${{ steps.tag_version.outputs.tag }}

      - name: Push tag to origin
        run: |
          git push origin ${{ steps.tag_version.outputs.tag }}

      - name: Push tag to main branch
        run: |
          git checkout main
          git merge release --no-ff --commit -m "Merging release branch"
          git push origin main

